package br.com.tecnonoticias.myException;

public class cc52259769 {
	
	public static void main(String[] args) {
		try {
			new Cliente().teste1();
		} catch (Exception e) {
			System.out.println("Encontrado uma falha no teste1! ");
		}
		
		
		new Cliente().teste2();
		
	}
}

class Cliente{

	void teste1() {
		new ClienteComum().cadastro("falha");
	}
	void teste2(){
		new ClienteExpecial().cadastro("falha");
	}


}

class ClienteComum extends cc52259769 {
	
	public void cadastro(String falha) throws IllegalArgumentException{
		if (falha.equals("falha")) {
			throw new IllegalArgumentException();
		}else{
			System.out.println("Passou no teste1 ");
		}
	}
}

class ClienteExpecial extends cc52259769 {
	
	public void cadastro(String falha) throws IllegalArgumentException{
		if (falha.equals("falha")) {
			throw new IllegalArgumentException();
		}else{
			System.out.println("Passou no teste2 ");
		}
	}

}
