package br.com.tecnonoticias.myException;

public class Cliente {

	void teste1() {
		new ClienteComum().cadastro("falha");
	}
	void teste2(){
		new ClienteExpecial().cadastro("falha");
	}

	public static void main(String[] args) {
		try {
			new cc52259769().teste1();
		} catch (Exception e) {
			System.out.println("Encontrado uma falha no teste1! ");
		}
		
		
			new cc52259769().teste2();
		
	}

}

class ClienteComum extends cc52259769 {
	
	public void cadastro(String falha) throws IllegalArgumentException{
		if (falha.equals("falha")) {
			throw new IllegalArgumentException();
		}else{
			System.out.println("Passou no teste1 ");
		}
	}
}

class ClienteExpecial extends cc52259769 {
	
	public void cadastro(String falha) throws IllegalArgumentException{
		if (falha.equals("falha")) {
			throw new IllegalArgumentException();
		}else{
			System.out.println("Passou no teste2 ");
		}
	}

}
