package br.com.tecnonoticias.myException;

public class cc52259769 {
	
	public static void main(String[] args) {
		try {
			new ClienteComum().teste1();
		} catch (Exception e) {
			System.out.println("Encontrado uma falha no teste1! ");
		}
		
		
		new Cliente().teste2();
		
	}
}

class Cliente{

	public static String teste1() {
		return "falha";
	}
	public static String teste2(){
		return "falha";
	}


}

class ClienteComum extends Cliente {
	
	public void cadastro(String falha) throws IllegalArgumentException{
		if (falha.equals("falha")) {
			throw new IllegalArgumentException();
		}else{
			System.out.println("Passou no teste1 ");
		}
	}
}

class ClienteExpecial extends Cliente {
	
	public void cadastro(String falha) throws IllegalArgumentException{
		if (falha.equals("falha")) {
			throw new IllegalArgumentException();
		}else{
			System.out.println("Passou no teste2 ");
		}
	}

}
